name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2.1.0
    - name: Docker Login

      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
